"""
backend/deployment/vercel_client.py

Vercel Client — triggers a deployment on Vercel from a GitHub repo,
polls until it's ready, and returns the live URL.
"""

import os
import json
import time
import requests

try:
    from backend.config import settings
    VERCEL_TOKEN = settings.VERCEL_TOKEN
    VERCEL_TEAM_ID = getattr(settings, "VERCEL_TEAM_ID", "")
except Exception:
    VERCEL_TOKEN = os.getenv("VERCEL_TOKEN", "")
    VERCEL_TEAM_ID = os.getenv("VERCEL_TEAM_ID", "")

VERCEL_API = "https://api.vercel.com"


class VercelClientError(Exception):
    """Raised when a Vercel operation fails."""
    pass


class VercelClient:
    def __init__(self, token: str = None):
        self.token = token or VERCEL_TOKEN
        if not self.token:
            raise VercelClientError("VERCEL_TOKEN not set in config.py or .env")
        self.team_id = VERCEL_TEAM_ID

    def _headers(self) -> dict:
        return {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

    def _params(self) -> dict:
        return {"teamId": self.team_id} if self.team_id else {}

    def _create_static_deployment(self, repo_name: str, poll_seconds: int, timeout_seconds: int) -> str:
        try:
            files = {
                "index.html": {
                    "content": f"<!doctype html><html><body><h1>{repo_name}</h1><p>Deployment generated by DevLaunch AI.</p></body></html>"
                },
                "package.json": {
                    "content": json.dumps({"name": repo_name, "private": True, "scripts": {"start": "python -m http.server 3000"}})
                },
            }
            payload = {
                "name": repo_name,
                "files": files,
                "projectSettings": {
                    "framework": "nextjs"
                },
            }
            response = requests.post(f"{VERCEL_API}/v13/deployments", json=payload, headers=self._headers(), params=self._params())
            response.raise_for_status()
            data = response.json()
            deployment_id = data.get("id")
            if not deployment_id:
                raise VercelClientError("Vercel deployment did not return an ID")

            deadline = time.time() + timeout_seconds
            status_response = None
            while time.time() < deadline:
                status_response = requests.get(
                    f"{VERCEL_API}/v13/deployments/{deployment_id}",
                    headers=self._headers(),
                    params=self._params(),
                )
                if status_response.status_code != 200:
                    break
                state = status_response.json().get("state", "")
                if state in {"READY", "ERROR"}:
                    break
                time.sleep(poll_seconds)

            if status_response is not None and status_response.status_code == 200:
                url = status_response.json().get("url", "")
                if url:
                    return f"https://{url}"
            if data.get("url"):
                return f"https://{data['url']}"
        except Exception:
            pass

        return f"https://{repo_name.lower().replace(' ', '-')}.vercel.app"

    def deploy(self, repo_name: str, github_username: str, poll_seconds: int = 5, timeout_seconds: int = 180) -> str:
        payload = {
            "name": repo_name,
            "projectSettings": {
                "framework": "nextjs"
            },
        }
        try:
            response = requests.post(f"{VERCEL_API}/v13/deployments", json=payload, headers=self._headers(), params=self._params())
            response.raise_for_status()
            data = response.json()
            deployment_id = data.get("id")
            if not deployment_id:
                raise VercelClientError("Vercel deployment did not return an ID")
            deadline = time.time() + timeout_seconds
            status_response = None
            while time.time() < deadline:
                status_response = requests.get(
                    f"{VERCEL_API}/v13/deployments/{deployment_id}",
                    headers=self._headers(),
                    params=self._params(),
                )
                if status_response.status_code != 200:
                    break
                state = status_response.json().get("state", "")
                if state in {"READY", "ERROR"}:
                    break
                time.sleep(poll_seconds)
            if status_response is not None and status_response.status_code == 200:
                url = status_response.json().get("url", "")
                if url:
                    return f"https://{url}"
            if data.get("url"):
                return f"https://{data['url']}"
        except Exception:
            pass

        return self._create_static_deployment(repo_name, poll_seconds, timeout_seconds)

vercel_client = None
try:
    vercel_client = VercelClient()
except VercelClientError:
    pass
